### ISSUE TITLE
Issue: is not safe for use in application extensions

### ISSUE THREAD

**Issue by jesus-mg-ios** [gumob/TLDExtractSwift#10]
<img width="692" alt="image" src="https://user-images.githubusercontent.com/85997060/125275028-ce974700-e30e-11eb-9971-715ec6888d6f.png">
Please, set the variable to avoid this warning

**Comment by jesus-mg-ios** [comment]
@gumob

**Comment by futamura** [comment]
Fixed in [4.0.1](https://github.com/futamura/TLDExtractSwift/releases/tag/4.0.1).

The framework build configurations now set `APPLICATION_EXTENSION_API_ONLY`, so linking TLDExtractSwift from an app extension no longer emits the warning. The library uses no extension-unsafe API, which the flag itself verifies — the build fails if any is introduced.

Two notes:

- Carthage users also need [PunycodeSwift 4.0.1](https://github.com/futamura/PunycodeSwift/releases/tag/4.0.1), released alongside this one with the same flag. Without it the warning persists via the dependency. A `carthage update` picks it up.
- SPM consumers were never affected; the setting applies to the Xcode framework targets only.

Apologies this sat unanswered for so long, and thanks for the report.
